### ISSUE TITLE
基础字体修改失效

### ISSUE THREAD

**Issue by baihuadeliaoluan** [Zuoqiu-Yingyi/siyuan-plugin-custom-fonts#16]
您好，自定义字体会出现失效的情况，并且更换任何主题或者基础主题都是这样，但是编辑字体可以修改。我试过重新建立新空间，发现新空间不会受到影响，但是之后使用插件修改多次后会再次出现。

**Comment by 135432weiman** [comment]
发现了问题所在，是插件表情包引起的冲突
