### ISSUE TITLE
思源3.1.16基础字体设置失效

### ISSUE THREAD

**Issue by 5kyfkr** [Zuoqiu-Yingyi/siyuan-plugin-custom-fonts#22]
![image](https://github.com/user-attachments/assets/b9fed9a4-e3fd-431e-baf4-bd0e24478986)
如题，基础字体现在更改没效果，全部是微软雅黑了，编辑器字体没问题

**Comment by HibernalGlow** [comment]
我css也失效了
@font-face {
    font-family: "Twitter Emoji";
    font-style: normal;
    font-weight: 400;
    font-display: swap;
    src: url("plugins/change-fonts/Twemoji.Mozilla-0.7.0.woff2");
}

@font-face {
	font-family: "霞鹜文楷屏幕阅读版";
	font-style: normal;
	src: url("plugins/change-fonts/霞鹜文楷屏幕阅读版.woff2");
}
@font-face {
	font-family: "systh";
	font-style: bold;
	src: url("plugins/change-fonts/SourceHanSerifCN-Heavy.woff2");
}

@font-face {
	font-family: "汉仪空山楷";
	font-style: normal;
	src: url("plugins/change-fonts/汉仪空山楷.woff2");
}

:root {
    --b3-font-family: "霞鹜文楷屏幕阅读版", "Twitter Emoji";
    --b3-font-family-protyle: "霞鹜文楷屏幕阅读版", "Twitter Emoji";
    --b3-font-family-code: "汉仪空山楷", "霞鹜文楷屏幕阅读版","Twemoji Mozilla";
    --b3-font-family-emoji: "Twitter Emoji", "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol", "Android Emoji", "EmojiSymbols";
}

**Comment by TCOTC** [comment]
新版默认主题会覆盖插件，需要适配一下，每行加个 `!important` 就行：

![image](https://github.com/user-attachments/assets/c5d49e05-34f9-45e2-a55d-239b911b806a)

**Comment by 5kyfkr** [comment]
> 新版默认主题会覆盖插件，需要适配一下，每行加个 `!important` 就行：
> 
感谢，在自定义代码片段里复制一遍--b3-font-family的设置，后面加个important就能修复
:root {
--b3-font-family: "霞鹜文楷屏幕阅读版", "Twitter Emoji" !important;
}

**Comment by Richie-Yi** [comment]
点赞，坐等大佬发布
