### ISSUE TITLE
插件很棒，就是不知道为啥经常失效

### ISSUE THREAD

**Issue by Glorenia** [Zuoqiu-Yingyi/siyuan-plugin-custom-fonts#8]
在集市里下载了一个Twitter emoji插件之后，就失效了。卸载了Twitter emoji插件之后也还是没有恢复。不知道具体是什么原因导致的。
更新：又尝试了一次，恢复了~可能是从卸载到恢复存在一些时滞吧

**Comment by Zuoqiu-Yingyi** [comment]
下次失效时可以试试开关一次 `设置` > `外观` > `代码片段` > `css` > `plugin-custom-fonts-style`
